title: AI

categories:

  - name: AI助手
    icon: fas fa-robot

    sites:

      - name: ChatGPT
        url: https://chatgpt.com
        description: AI助手

      - name: Claude
        url: https://claude.ai
        description: Anthropic AI助手

      - name: Gemini
        url: https://gemini.google.com
        description: Google AI助手

      - name: Deepseek
        url: https://www.deepseek.com/
        description: Deepseek AI助手


  - name: AI开发工具
    icon: fas fa-code

    sites:

      - name: GitHub
        url: https://github.com
        description: 开源代码平台

      - name: Hugging Face
        url: https://huggingface.co
        description: AI模型社区

      - name: OpenAI Platform
        url: https://platform.openai.com
        description: AI开发接口

      - name: CSDN
        url: https://www.csdn.net/
        description: 技术开发社区

      - name: CSDN AI Coding
        url: https://aicoding.csdn.net/
        description: AI编程平台

      - name: GitCN
        url: https://gitcn.org/
        description: Git资源社区
