title: 常用

categories:
  - name: 常用网站
    icon: fas fa-star

    sites:

      - name: Google翻译
        url: https://translate.google.com/?hl=zh-CN&sl=auto&tl=zh-CN&op=translate
        description: 翻译

      - name: GitHub
        url: https://github.com
        description: 代码仓库

      - name: ChatGPT
        url: https://chatgpt.com
        description: AI助手
        
      - name: PubMed
        url: https://pubmed.ncbi.nlm.nih.gov
        description: 文献检索
